apiVersion: v1beta1
kind: Service
id: elasticsearch-logging
containerPort: es-port
port: 9200
labels:
  name: elasticsearch-logging
  kubernetes.io/cluster-service: "true"
selector:
  name: elasticsearch-logging
createExternalLoadBalancer: true
