
apiVersion: v1beta3
kind: Service
metadata:
  labels:
    app: kibana-logging
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Kibana"
  name: kibana-logging
spec:
  ports:
  - port: 5601
    protocol: TCP
    targetPort: kibana-port
  selector:
    app: kibana-logging
