apiVersion: v1beta3
kind: ReplicationController
metadata:
  labels:
    name: kibana-logging
    kubernetes.io/cluster-service: "true"
  name: kibana-logging
spec:
  replicas: 1
  selector:
    name: kibana-logging
  template:
    metadata:
      labels:
        kubernetes.io/cluster-service: "true"
        name: kibana-logging
    spec:
      containers:
      - name: kibana-logging
        image: gcr.io/google_containers/kibana:1.3
        env:
          - name: "ELASTICSEARCH_URL"
            value: "http://elasticsearch-logging:9200"
        ports:
        - containerPort: 5601
          name: kibana-port
          protocol: TCP
